server:
  tomcat:
    threads:
      max: 35
    max-connections: 1024
    accept-count: 242

spring:
  profiles:
    active:
  application:
    name: oreum
  datasource:
    url: jdbc:h2:mem:database;DB_CLOSE_DELAY=-1;MODE=MySQL
    hikari:
      maximum-pool-size: 8
  sql:
    init:
      mode: embedded
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      max-file-size: 20MB
      max-request-size: 20MB
  jackson:
    time-zone: Asia/Seoul
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    path: swagger-ui.html
    persist-authorization: true

#logging:
#  level:
#    com.oreum.zzarit: INFO
#  file:
#    name: /logs/backend.log
#  pattern:
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [trackId=%X{trackId}] %-5level %logger{36} - %msg%n"
#  logback:
#    rollingpolicy:
#      file-name-pattern: /logs/backend.%d{yyyy-MM-dd}.%i.log
#      max-file-size: 100MB
#      max-history: 14


security:
  jwt:
    token:
      access-secret-key: testAccessSecretKeytestAccessSecretKeytestAccessSecretKeytestAccessSecretKeytest
      refresh-secret-key: testRefreshSecretKeytestRefreshSecretKeytestRefreshSecretKeytestRefreshSecretKeytest
      refresh-token-expired: 14d
      access-token-expired: 1d

#auth:
#  connect-timeout-length: 3s
#  read-timeout-length: 3s

management:
  endpoints:
    web:
      exposure:
        include: health
      path-mapping:
        health: health-check
      base-path: /

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: JSESSIONID
