spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    defer-datasource-initialization: false
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        # SQL 포매팅 비활성화
        format_sql: false
        # SQL 주석 비활성화
        use_sql_comments: false

    hibernate:
      ddl-auto: update

# 로깅 레벨 설정으로 SQL 로그 완전 차단
logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    org.springframework.jdbc.core.JdbcTemplate: OFF
    org.springframework.jdbc.core.StatementCreatorUtils: OFF

security:
  jwt:
    token:
      access-secret-key: ${JWT_ACCESS_SECRET_KEY}
      refresh-secret-key: ${JWT_REFRESH_SECRET_KEY}
      refresh-token-expired: 14d
      access-token-expired: 1d