name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build without tests
        run: ./gradlew clean build -x test

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm/v7 \
            -t ${{ secrets.DOCKER_USERNAME }}/oreum:latest \
            . \
            --push

      - name: SSH into Raspberry Pi and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/oreum:latest
            docker compose -f /home/pi/oreum/compose.yml --env-file /home/pi/oreum/.env up -d
